-- TABLE
DROP
    TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(64) NOT NULL,
 `job` VARCHAR(64) NOT NULL,
 `notes` VARCHAR(256) DEFAULT '',
 `status` TINYINT DEFAULT '1', 
 `flag` TINYINT DEFAULT '0',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 -- INDEX
 PRIMARY KEY (`id`) -- FOR FOREIGN KEY
) ENGINE = INNODB;

-- TABLE
DROP
    TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(64) NOT NULL,
 `description` VARCHAR(256) DEFAULT '',
 `status` TINYINT DEFAULT '1', 
 `flag` TINYINT DEFAULT '0',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 -- INDEX
 PRIMARY KEY (`id`) -- FOR FOREIGN KEY
) ENGINE = INNODB;

-- TABLE
DROP
    TABLE IF EXISTS `activities`;
CREATE TABLE IF NOT EXISTS `activities` (
 -- COLUMNS,
 `id` INT NOT NULL AUTO_INCREMENT,
 `fk_user_id` INT,
 `fk_categories_id` INT,
 `expense_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `expense` INT,
 `total_expense` INT,
 `notes` VARCHAR(256) DEFAULT '',
 `status` TINYINT DEFAULT '1', 
 `flag` TINYINT DEFAULT '0',
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
-- INDEX
 PRIMARY KEY (`id`),
 KEY `fk_user_id` (`fk_user_id`),
 CONSTRAINT `activities_ibfk_1` FOREIGN KEY (`fk_user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
 KEY `fk_categories_id` (`fk_categories_id`),
 CONSTRAINT `activities_ibfk_2` FOREIGN KEY (`fk_categories_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE
) ENGINE = INNODB;
